# Generated by Django 5.2.7 on 2025-11-13 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(default='ubuntu:22.04', max_length=200)),
                ('ram', models.IntegerField(default=1024, help_text='RAM in MB')),
                ('cpu', models.FloatField(default=1.0, help_text='CPU cores')),
                ('storage', models.IntegerField(default=10240, help_text='Storage in MB')),
                ('container_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running')], default='stopped', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
